[package]
name = "agent-api-services"
version = "0.1.0"
edition = "2024"

[dependencies]
agent-workflows = { path = "../agent-workflows" }
anyhow = "1.0.104"
axum = "0.8.9"
dotenvy = "0.15.7"
sqlx = { version = "0.9", features = ["postgres", "runtime-tokio", "macros", "time"] }
tokio = { version = "1", features = ["full"] }

[lints]
workspace = true
